<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" total="7" passed="0">
  <reporter-output>
    <line>
      <![CDATA[url: /c/designerBooking/v2/addNew]]>
    </line>
    <line>
      <![CDATA[请求参数: {districtCode=310101, userRealname=李四, provinceCode=aaa, userMobile=150218741k5, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
    </line>
    <line>
      <![CDATA[url: /c/designerBooking/v2/addNew]]>
    </line>
    <line>
      <![CDATA[请求参数: {districtCode=aa, userRealname=张三, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
    </line>
    <line>
      <![CDATA[url: /c/designerBooking/v2/addNew]]>
    </line>
    <line>
      <![CDATA[请求参数: {districtCode=310101, userRealname=李四, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=aaaabbbb}]]>
    </line>
    <line>
      <![CDATA[url: /c/designerBooking/v2/addNew]]>
    </line>
    <line>
      <![CDATA[请求参数: {districtCode=310101, userRealname=李四, provinceCode=310000, userMobile=15021874195, cityCode=oo, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
    </line>
    <line>
      <![CDATA[url: /c/designerBooking/v2/addNew]]>
    </line>
    <line>
      <![CDATA[请求参数: {districtCode=310101, userRealname=李四, provinceCode=310000, userMobile=150218741k5, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
    </line>
    <line>
      <![CDATA[url: /c/designerBooking/v2/addNew]]>
    </line>
    <line>
      <![CDATA[url: /c/designerBooking/v2/addNew]]>
    </line>
    <line>
      <![CDATA[请求参数: {districtCode=310101, userRealname=张三, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
    </line>
    <line>
      <![CDATA[请求参数: {districtCode=310101, extendParam=kkkk, userRealname=张三, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
    </line>
    <line>
      <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452161,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
    </line>
    <line>
      <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452140,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
    </line>
    <line>
      <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452128,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
    </line>
    <line>
      <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452142,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
    </line>
    <line>
      <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452161,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
    </line>
    <line>
      <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452101,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
    </line>
    <line>
      <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452120,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="3678" started-at="2018-05-31T08:30:48Z" finished-at="2018-05-31T08:30:51Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="3678" started-at="2018-05-31T08:30:48Z" finished-at="2018-05-31T08:30:51Z">
      <class name="testCase.AddNewBookingOrderTest">
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:testCase.AddNewBookingOrderTest@694e1548]" name="beforeClass" is-config="true" duration-ms="426" started-at="2018-05-31T16:30:48Z" finished-at="2018-05-31T16:30:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="FAIL" signature="addNewBookingOrder(java.util.Map)[pri:0, instance:testCase.AddNewBookingOrderTest@694e1548]" name="addNewBookingOrder" duration-ms="2449" started-at="2018-05-31T16:30:49Z" description="预约提交" data-provider="providerData" finished-at="2018-05-31T16:30:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{districtCode=310101, expectResult={"code":200,"message":"成功","dataMap":"201704281500114983"}, extendParam=kkkk, userRealname=张三, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535, url=/c/designerBooking/v2/addNew, testName=添加冗余参数}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[response返回的statuCode不是200	 expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: response返回的statuCode不是200	 expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at comm.ParametersSet.parseResult(ParametersSet.java:133)
	at testCase.AddNewBookingOrderTest.addNewBookingOrder(AddNewBookingOrderTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[url: /c/designerBooking/v2/addNew]]>
            </line>
            <line>
              <![CDATA[请求参数: {districtCode=310101, extendParam=kkkk, userRealname=张三, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
            </line>
            <line>
              <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452101,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
            </line>
          </reporter-output>
        </test-method> <!-- addNewBookingOrder -->
        <test-method status="FAIL" signature="addNewBookingOrder(java.util.Map)[pri:0, instance:testCase.AddNewBookingOrderTest@694e1548]" name="addNewBookingOrder" duration-ms="2420" started-at="2018-05-31T16:30:49Z" description="预约提交" data-provider="providerData" finished-at="2018-05-31T16:30:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{districtCode=310101, expectResult=, userRealname=李四, provinceCode=310000, userMobile=150218741k5, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535, url=/c/designerBooking/v2/addNew, testName=无效手机号}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[response返回的statuCode不是200	 expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: response返回的statuCode不是200	 expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at comm.ParametersSet.parseResult(ParametersSet.java:133)
	at testCase.AddNewBookingOrderTest.addNewBookingOrder(AddNewBookingOrderTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[url: /c/designerBooking/v2/addNew]]>
            </line>
            <line>
              <![CDATA[请求参数: {districtCode=310101, userRealname=李四, provinceCode=310000, userMobile=150218741k5, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
            </line>
            <line>
              <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452140,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
            </line>
          </reporter-output>
        </test-method> <!-- addNewBookingOrder -->
        <test-method status="FAIL" signature="addNewBookingOrder(java.util.Map)[pri:0, instance:testCase.AddNewBookingOrderTest@694e1548]" name="addNewBookingOrder" duration-ms="2419" started-at="2018-05-31T16:30:49Z" description="预约提交" data-provider="providerData" finished-at="2018-05-31T16:30:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{districtCode=aa, expectResult=, userRealname=张三, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535, url=/c/designerBooking/v2/addNew, testName=无效districtCode}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[response返回的statuCode不是200	 expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: response返回的statuCode不是200	 expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at comm.ParametersSet.parseResult(ParametersSet.java:133)
	at testCase.AddNewBookingOrderTest.addNewBookingOrder(AddNewBookingOrderTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[url: /c/designerBooking/v2/addNew]]>
            </line>
            <line>
              <![CDATA[请求参数: {districtCode=aa, userRealname=张三, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
            </line>
            <line>
              <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452161,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
            </line>
          </reporter-output>
        </test-method> <!-- addNewBookingOrder -->
        <test-method status="FAIL" signature="addNewBookingOrder(java.util.Map)[pri:0, instance:testCase.AddNewBookingOrderTest@694e1548]" name="addNewBookingOrder" duration-ms="2419" started-at="2018-05-31T16:30:49Z" description="预约提交" data-provider="providerData" finished-at="2018-05-31T16:30:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{districtCode=310101, expectResult=, userRealname=李四, provinceCode=aaa, userMobile=150218741k5, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535, url=/c/designerBooking/v2/addNew, testName=无效provinceCode}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[response返回的statuCode不是200	 expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: response返回的statuCode不是200	 expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at comm.ParametersSet.parseResult(ParametersSet.java:133)
	at testCase.AddNewBookingOrderTest.addNewBookingOrder(AddNewBookingOrderTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[url: /c/designerBooking/v2/addNew]]>
            </line>
            <line>
              <![CDATA[请求参数: {districtCode=310101, userRealname=李四, provinceCode=aaa, userMobile=150218741k5, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
            </line>
            <line>
              <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452128,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
            </line>
          </reporter-output>
        </test-method> <!-- addNewBookingOrder -->
        <test-method status="FAIL" signature="addNewBookingOrder(java.util.Map)[pri:0, instance:testCase.AddNewBookingOrderTest@694e1548]" name="addNewBookingOrder" duration-ms="2443" started-at="2018-05-31T16:30:49Z" description="预约提交" data-provider="providerData" finished-at="2018-05-31T16:30:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{districtCode=310101, expectResult={"code":200,"message":"成功","dataMap":"201704281500114983"}, userRealname=张三, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535, url=/c/designerBooking/v2/addNew, testName=预约}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[response返回的statuCode不是200	 expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: response返回的statuCode不是200	 expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at comm.ParametersSet.parseResult(ParametersSet.java:133)
	at testCase.AddNewBookingOrderTest.addNewBookingOrder(AddNewBookingOrderTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[url: /c/designerBooking/v2/addNew]]>
            </line>
            <line>
              <![CDATA[请求参数: {districtCode=310101, userRealname=张三, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
            </line>
            <line>
              <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452161,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
            </line>
          </reporter-output>
        </test-method> <!-- addNewBookingOrder -->
        <test-method status="FAIL" signature="addNewBookingOrder(java.util.Map)[pri:0, instance:testCase.AddNewBookingOrderTest@694e1548]" name="addNewBookingOrder" duration-ms="2418" started-at="2018-05-31T16:30:49Z" description="预约提交" data-provider="providerData" finished-at="2018-05-31T16:30:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{districtCode=310101, expectResult=, userRealname=李四, provinceCode=310000, userMobile=15021874195, cityCode=oo, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535, url=/c/designerBooking/v2/addNew, testName=无效cityCode}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[response返回的statuCode不是200	 expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: response返回的statuCode不是200	 expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at comm.ParametersSet.parseResult(ParametersSet.java:133)
	at testCase.AddNewBookingOrderTest.addNewBookingOrder(AddNewBookingOrderTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[url: /c/designerBooking/v2/addNew]]>
            </line>
            <line>
              <![CDATA[请求参数: {districtCode=310101, userRealname=李四, provinceCode=310000, userMobile=15021874195, cityCode=oo, designerOpenId=f14ea222-bc1c-4dcc-b698-4945a6733535}]]>
            </line>
            <line>
              <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452142,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
            </line>
          </reporter-output>
        </test-method> <!-- addNewBookingOrder -->
        <test-method status="FAIL" signature="addNewBookingOrder(java.util.Map)[pri:0, instance:testCase.AddNewBookingOrderTest@694e1548]" name="addNewBookingOrder" duration-ms="2449" started-at="2018-05-31T16:30:49Z" description="预约提交" data-provider="providerData" finished-at="2018-05-31T16:30:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{districtCode=310101, expectResult=, userRealname=李四, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=aaaabbbb, url=/c/designerBooking/v2/addNew, testName=无效的designerOpenId}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[response返回的statuCode不是200	 expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: response返回的statuCode不是200	 expected [200] but found [404]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:135)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:389)
	at comm.ParametersSet.parseResult(ParametersSet.java:133)
	at testCase.AddNewBookingOrderTest.addNewBookingOrder(AddNewBookingOrderTest.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:75)
	at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:14)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[url: /c/designerBooking/v2/addNew]]>
            </line>
            <line>
              <![CDATA[请求参数: {districtCode=310101, userRealname=李四, provinceCode=310000, userMobile=15021874195, cityCode=310100, designerOpenId=aaaabbbb}]]>
            </line>
            <line>
              <![CDATA[/c/designerBooking/v2/addNew返回： {"timestamp":1527755452120,"status":404,"error":"Not Found","message":"No message available","path":"/c/designerBooking/v2/addNew"}]]>
            </line>
          </reporter-output>
        </test-method> <!-- addNewBookingOrder -->
      </class> <!-- testCase.AddNewBookingOrderTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
