<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[【正常用例】:获取怀化天气成功!]]>
    </line>
    <line>
      <![CDATA[<p><span style="color:#FF0000">请求地址: http://www.weather.com.cn/data/cityinfo/101251201.html</span></p>]]>
    </line>
    <line>
      <![CDATA[【返回结果】: {"weatherinfo":{"city":"怀化","cityid":"101251201","temp1":"16℃","temp2":"22℃","weather":"阵雨转阴","img1":"n3.gif","img2":"d2.gif","ptime":"18:00"}}]]>
    </line>
    <line>
      <![CDATA[<p>【用例结果】: resultCode=>expected: 怀化 ,actual: null</p>]]>
    </line>
    <line>
      <![CDATA[【正常用例】:获取会同天气成功!]]>
    </line>
    <line>
      <![CDATA[<p><span style="color:#FF0000">请求地址: http://www.weather.com.cn/data/cityinfo/101251206.html</span></p>]]>
    </line>
    <line>
      <![CDATA[【返回结果】: {"weatherinfo":{"city":"会同","cityid":"101251206","temp1":"17℃","temp2":"22℃","weather":"中到大雨转小雨","img1":"n22.gif","img2":"d7.gif","ptime":"18:00"}}]]>
    </line>
    <line>
      <![CDATA[<p>【用例结果】: resultCode=>expected: 会同 ,actual: null</p>]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="533" started-at="2018-05-22T07:44:16Z" finished-at="2018-05-22T07:44:17Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="533" started-at="2018-05-22T07:44:16Z" finished-at="2018-05-22T07:44:17Z">
      <class name="util.TestCase">
        <test-method status="FAIL" signature="getHuaihua()[pri:0, instance:util.TestCase@4b4523f8]" name="getHuaihua" duration-ms="457" started-at="2018-05-22T15:44:16Z" finished-at="2018-05-22T15:44:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [怀化] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [怀化] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:130)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at util.TestCase.resultCheck(TestCase.java:42)
	at util.TestCase.getHuaihua(TestCase.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[【正常用例】:获取怀化天气成功!]]>
            </line>
            <line>
              <![CDATA[<p><span style="color:#FF0000">请求地址: http://www.weather.com.cn/data/cityinfo/101251201.html</span></p>]]>
            </line>
            <line>
              <![CDATA[【返回结果】: {"weatherinfo":{"city":"怀化","cityid":"101251201","temp1":"16℃","temp2":"22℃","weather":"阵雨转阴","img1":"n3.gif","img2":"d2.gif","ptime":"18:00"}}]]>
            </line>
            <line>
              <![CDATA[<p>【用例结果】: resultCode=>expected: 怀化 ,actual: null</p>]]>
            </line>
          </reporter-output>
        </test-method> <!-- getHuaihua -->
        <test-method status="FAIL" signature="getHuitong()[pri:1, instance:util.TestCase@4b4523f8]" name="getHuitong" duration-ms="53" started-at="2018-05-22T15:44:17Z" finished-at="2018-05-22T15:44:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [会同] but found [null]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [会同] but found [null]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertEqualsImpl(Assert.java:130)
	at org.testng.Assert.assertEquals(Assert.java:116)
	at org.testng.Assert.assertEquals(Assert.java:190)
	at org.testng.Assert.assertEquals(Assert.java:200)
	at util.TestCase.resultCheck(TestCase.java:42)
	at util.TestCase.getHuitong(TestCase.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[【正常用例】:获取会同天气成功!]]>
            </line>
            <line>
              <![CDATA[<p><span style="color:#FF0000">请求地址: http://www.weather.com.cn/data/cityinfo/101251206.html</span></p>]]>
            </line>
            <line>
              <![CDATA[【返回结果】: {"weatherinfo":{"city":"会同","cityid":"101251206","temp1":"17℃","temp2":"22℃","weather":"中到大雨转小雨","img1":"n22.gif","img2":"d7.gif","ptime":"18:00"}}]]>
            </line>
            <line>
              <![CDATA[<p>【用例结果】: resultCode=>expected: 会同 ,actual: null</p>]]>
            </line>
          </reporter-output>
        </test-method> <!-- getHuitong -->
      </class> <!-- util.TestCase -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
